// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see https://docs.c9.io/custom_runners.html
{
    "cmd": [
        "python2",
        "-m",
        "ikpdb",
        "$file"
    ],

    "info": "Launching debugging for $project_path$file_name ...",
    "debugport": 15470,
    "debugger": "pythondebug",
    "executable": "$file_path/$file_name",
    "maxdepth": 50,
    "env": {},
    "selector": "^.*\\.py$"



}
